export const data = [
  {
    plane: "Free",
    price: "$0/month",
    user: "Single User",
    storage: "50GB Storage",
    public: "Unlimited Public Projects",
    community: "Community Access",
    private: "Unlimited Private Project",
    support: "Dedicated Phone Support",
    domain: "Free Subdomain",
    reports: "Monthly Status Reports",
    planeIcon: true,
    priceIcon: true,
    userIcon: true,
    storageIcon: false,
    publicIcon: true,
    communityIcon: true,
    privateIcon: false,
    supportIcon: false,
    domainIcon: false,
    reportsIcon: false,
  },
  {
    plane: "Plus",
    price: "$9/month",
    user: "5 User",
    storage: "50GB Storage",
    public: "Unlimited Public Projects",
    community: "Community Access",
    private: "Unlimited Private Project",
    support: "Dedicated Phone Support",
    domain: "Free Subdomain",
    reports: "Monthly Status Reports",
    planeIcon: true,
    priceIcon: true,
    userIcon: true,
    publicIcon: true,
    communityIcon: true,
    privateIcon: true,
    supportIcon: true,
    domainIcon: false,
    reportsIcon: false,
  },
  {
    plane: "Pro",
    price: "$49/month",
    user: "Unlimited User",
    storage: "50GB Storage",
    public: "Unlimited Public Projects",
    community: "Community Access",
    private: "Unlimited Private Project",
    support: "Dedicated Phone Support",
    domain: "Free Subdomain",
    reports: "Monthly Status Reports",
    planeIcon: true,
    priceIcon: true,
    userIcon: true,
    publicIcon: true,
    communityIcon: true,
    privateIcon: true,
    supportIcon: true,
    domainIcon: true,
    reportsIcon: true,
  },
];
